### ISSUE TITLE
i still cant tell what application is this

### ISSUE THREAD

**Issue by xuatz** [Aeolun/writer2#5]
but im surprised to see active development!
maybe i should finally checkout the code on local lol

**Comment by Aeolun** [comment]
It’s for writing books ;) I’m perpetually dissatisfied with other software.

**Comment by Aeolun** [comment]
I guess I should update the readme at some point

**Comment by xuatz** [comment]
interesting... do you publish them anywhere?

**Comment by Aeolun** [comment]
Well, as of now I probably spent more time building than writing, but what I have is here:  https://www.royalroad.com/fiction/85005/survival-book-of-days

It’s pretty bad writing right now, but it’s fun and I’m sure it’ll get better 🤷 guess you have to be into the isekai things to enjoy it though.
